title = "Robin Hood (1973)"
director = "Wolfgang Reitherman"
summary = """
An amiable rooster called Alan-a-Dale (Roger Miller) tells stories and sings songs of the heroic Robin Hood (Brian Bedford) and his trusty sidekick, Little John (Phil Harris), in this animated animal-themed adaptation of the legendary story. When evil Prince John (Peter Ustinov) deputizes the Sheriff of Nottingham (Pat Buttram) to collect unreasonable taxes from the animals of Sherwood Forest, Robin, Little John and the other merry men wage a lighthearted battle against their evil foes.
"""
