---
# - name: Install Caddy Repository
#   apt_repository:
#     state: present
#     repo: deb [trusted=yes] https://apt.fury.io/caddy focal main
#     filename: caddy-fury
# - name: Install Caddy
#   apt:
#     name:
#       - caddy

- name: Install Caddy
  apt:
    state: present
    deb: '{{ caddy_deb }}'

- name: Generate Password
  shell: echo '{{ web_password }}' | caddy hash-password -algorithm scrypt
  register: hashed_password

- name: Set Fact
  set_fact:
    web_password_hashed: '{{ hashed_password.stdout }}'

- name: Template Configuration
  template:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile

- name: Start Systemd Caddy
  systemd:
    name: caddy
    state: started
    daemon_reload: yes
    enabled: yes

- name: Reload caddy
  command: systemctl reload caddy
