---
- name: Update Cache & Upgrade
  apt:
    update_cache: yes
    upgrade: safe
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: Create '{{ user }}' User
  import_tasks: user.yml
  tags: user

- name: Set Timezone
  timezone:
    name: America/Los_Angeles

- name: rsync code and movie
  import_tasks: rsync.yml
  tags: rsync

- name: Update Firewall
  import_tasks: ufw.yml
  tags: ufw

- name: Systemd Start GoLang
  import_tasks: systemd.yml
  tags: systemd

- name: Configure and Start Caddy
  import_tasks: caddy.yml
  tags: caddy
