---
- name: Sync Source Code
  become_user: '{{ user }}'
  ansible.posix.synchronize:
    archive: yes
    private_key: ../../../../ssh_key
    src: ../../../../
    dest: /home/{{ user }}/{{ folder_name }}
    delete: yes
    rsync_opts:
      - '--exclude'
      - 'node_modules'
      - '--exclude'
      - local

- name: Sync Movie
  become_user: '{{ user }}'
  tags: rsync-movie
  ansible.posix.synchronize:
    archive: yes
    private_key: ../../../../ssh_key
    src: ../../../../local
    dest: /home/{{ user }}/{{ folder_name }}
    delete: yes
