---
- name: Copy System Unit
  template:
    src: '{{ folder_name }}.service'
    dest: /etc/systemd/system

- name: Start and Enable {{ folder_name }}.service
  systemd:
    name: '{{ folder_name }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
