---
- name: Create Op User
  user:
    state: present
    name: '{{ user }}'
    append: yes
    comment: Operator
    groups:
      - sudo
    password: "{{ password | password_hash('sha512') }}"
    shell: /bin/bash
